name: "Website CI"

on:
  push:
    branches:
      - master
  issues:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  setup-build-deploy:
    name: Setup Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "13"
      - name: Install Dependencies
        run: npm install
      - name: Build Gatsby Website
        run: npm run build
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --dir=public --prod
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
        # uses: jsmrcaga/action-netlify-deploy@v1.1.0
        # with:
        #   production-branch: master
        #   publish-dir: "./public"
        #   deploy-message: "Deploy from GitHub Actions"
        # env:
        #   NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
        #   NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
