name: "Website CI"

on:
  push:
    branches:
      - master
  issues:

jobs:
  setup-build-deploy:
    name: Setup Build and Deploy
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      # - name: Install Dependencies
      #   run: |
      #     rm package-lock.json;
      #     rm -rf node_modules;
      #     npm install;
      - name: Build and Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: public
